// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Message, unionToMessage, unionListToMessage } from '../dot-dschema/message.js';


export class FlatBufferType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FlatBufferType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFlatBufferType(bb:flatbuffers.ByteBuffer, obj?:FlatBufferType):FlatBufferType {
  return (obj || new FlatBufferType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFlatBufferType(bb:flatbuffers.ByteBuffer, obj?:FlatBufferType):FlatBufferType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FlatBufferType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageType():Message {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Message.NONE;
}

message<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startFlatBufferType(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessageType(builder:flatbuffers.Builder, messageType:Message) {
  builder.addFieldInt8(0, messageType, Message.NONE);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endFlatBufferType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFlatBufferTypeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedFlatBufferTypeBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createFlatBufferType(builder:flatbuffers.Builder, messageType:Message, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  FlatBufferType.startFlatBufferType(builder);
  FlatBufferType.addMessageType(builder, messageType);
  FlatBufferType.addMessage(builder, messageOffset);
  return FlatBufferType.endFlatBufferType(builder);
}
}
