// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ScoreUpdateResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScoreUpdateResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScoreUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:ScoreUpdateResponse):ScoreUpdateResponse {
  return (obj || new ScoreUpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScoreUpdateResponse(bb:flatbuffers.ByteBuffer, obj?:ScoreUpdateResponse):ScoreUpdateResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScoreUpdateResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

score():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startScoreUpdateResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addScore(builder:flatbuffers.Builder, score:number) {
  builder.addFieldFloat32(1, score, 0.0);
}

static endScoreUpdateResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScoreUpdateResponse(builder:flatbuffers.Builder, sessionId:number, score:number):flatbuffers.Offset {
  ScoreUpdateResponse.startScoreUpdateResponse(builder);
  ScoreUpdateResponse.addSessionId(builder, sessionId);
  ScoreUpdateResponse.addScore(builder, score);
  return ScoreUpdateResponse.endScoreUpdateResponse(builder);
}
}
