// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AdminSetStartingPhase {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AdminSetStartingPhase {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAdminSetStartingPhase(bb:flatbuffers.ByteBuffer, obj?:AdminSetStartingPhase):AdminSetStartingPhase {
  return (obj || new AdminSetStartingPhase()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAdminSetStartingPhase(bb:flatbuffers.ByteBuffer, obj?:AdminSetStartingPhase):AdminSetStartingPhase {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AdminSetStartingPhase()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

phaseIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startAdminSetStartingPhase(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addPhaseIndex(builder:flatbuffers.Builder, phaseIndex:number) {
  builder.addFieldInt8(1, phaseIndex, 0);
}

static endAdminSetStartingPhase(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAdminSetStartingPhase(builder:flatbuffers.Builder, sessionId:number, phaseIndex:number):flatbuffers.Offset {
  AdminSetStartingPhase.startAdminSetStartingPhase(builder);
  AdminSetStartingPhase.addSessionId(builder, sessionId);
  AdminSetStartingPhase.addPhaseIndex(builder, phaseIndex);
  return AdminSetStartingPhase.endAdminSetStartingPhase(builder);
}
}
