// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AdminModifyAsteroidSpeed {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AdminModifyAsteroidSpeed {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAdminModifyAsteroidSpeed(bb:flatbuffers.ByteBuffer, obj?:AdminModifyAsteroidSpeed):AdminModifyAsteroidSpeed {
  return (obj || new AdminModifyAsteroidSpeed()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAdminModifyAsteroidSpeed(bb:flatbuffers.ByteBuffer, obj?:AdminModifyAsteroidSpeed):AdminModifyAsteroidSpeed {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AdminModifyAsteroidSpeed()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

speedMod():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startAdminModifyAsteroidSpeed(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addSpeedMod(builder:flatbuffers.Builder, speedMod:number) {
  builder.addFieldFloat32(1, speedMod, 0.0);
}

static endAdminModifyAsteroidSpeed(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAdminModifyAsteroidSpeed(builder:flatbuffers.Builder, sessionId:number, speedMod:number):flatbuffers.Offset {
  AdminModifyAsteroidSpeed.startAdminModifyAsteroidSpeed(builder);
  AdminModifyAsteroidSpeed.addSessionId(builder, sessionId);
  AdminModifyAsteroidSpeed.addSpeedMod(builder, speedMod);
  return AdminModifyAsteroidSpeed.endAdminModifyAsteroidSpeed(builder);
}
}
