// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AdminSetBotCount {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AdminSetBotCount {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAdminSetBotCount(bb:flatbuffers.ByteBuffer, obj?:AdminSetBotCount):AdminSetBotCount {
  return (obj || new AdminSetBotCount()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAdminSetBotCount(bb:flatbuffers.ByteBuffer, obj?:AdminSetBotCount):AdminSetBotCount {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AdminSetBotCount()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

botCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startAdminSetBotCount(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addBotCount(builder:flatbuffers.Builder, botCount:number) {
  builder.addFieldInt32(1, botCount, 0);
}

static endAdminSetBotCount(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAdminSetBotCount(builder:flatbuffers.Builder, sessionId:number, botCount:number):flatbuffers.Offset {
  AdminSetBotCount.startAdminSetBotCount(builder);
  AdminSetBotCount.addSessionId(builder, sessionId);
  AdminSetBotCount.addBotCount(builder, botCount);
  return AdminSetBotCount.endAdminSetBotCount(builder);
}
}
