"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.ETriggerState = void 0;
var ETriggerState;
(function (ETriggerState) {
    ETriggerState[ETriggerState["None"] = 0] = "None";
    ETriggerState[ETriggerState["Triggered"] = 1] = "Triggered";
    ETriggerState[ETriggerState["Started"] = 2] = "Started";
    ETriggerState[ETriggerState["Ongoing"] = 4] = "Ongoing";
    ETriggerState[ETriggerState["Canceled"] = 8] = "Canceled";
    ETriggerState[ETriggerState["Completed"] = 16] = "Completed";
})(ETriggerState || (exports.ETriggerState = ETriggerState = {}));
//# sourceMappingURL=etrigger-state.js.map