// automatically generated by the FlatBuffers compiler, do not modify

export enum GlobalInputEnums {
  Min = 0,
  None = 1,
  TapSlash = 2,
  Drawing = 3,
  Buttons = 4,
  TapAsteroid = 5,
  PointTap = 6,
  Max = 7
}
