"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.LinearColor = void 0;
var LinearColor = /** @class */ (function () {
    function LinearColor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    LinearColor.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    LinearColor.prototype.r = function () {
        return this.bb.readFloat32(this.bb_pos);
    };
    LinearColor.prototype.g = function () {
        return this.bb.readFloat32(this.bb_pos + 4);
    };
    LinearColor.prototype.b = function () {
        return this.bb.readFloat32(this.bb_pos + 8);
    };
    LinearColor.prototype.a = function () {
        return this.bb.readFloat32(this.bb_pos + 12);
    };
    LinearColor.sizeOf = function () {
        return 16;
    };
    LinearColor.createLinearColor = function (builder, r, g, b, a) {
        builder.prep(4, 16);
        builder.writeFloat32(a);
        builder.writeFloat32(b);
        builder.writeFloat32(g);
        builder.writeFloat32(r);
        return builder.offset();
    };
    return LinearColor;
}());
exports.LinearColor = LinearColor;
//# sourceMappingURL=linear-color.js.map