// automatically generated by the FlatBuffers compiler, do not modify

import { ClientLoginResponse } from '../wsschema/client-login-response.js';
import { GenericBatchRequest } from '../wsschema/generic-batch-request.js';
import { GenericBatchResponse } from '../wsschema/generic-batch-response.js';
import { GlobalInputResponse } from '../wsschema/global-input-response.js';
import { JsonToBinaryRequest } from '../wsschema/json-to-binary-request.js';
import { JsonToBinaryResponse } from '../wsschema/json-to-binary-response.js';
import { LateConnectPayloadRequest } from '../wsschema/late-connect-payload-request.js';
import { LateConnectPayloadResponse } from '../wsschema/late-connect-payload-response.js';
import { MediaPlaneLoginRequest } from '../wsschema/media-plane-login-request.js';
import { MobileToMediaPlaneLoginRequest } from '../wsschema/mobile-to-media-plane-login-request.js';
import { MobileToMediaPlaneLogoutRequest } from '../wsschema/mobile-to-media-plane-logout-request.js';
import { PhaseResponse } from '../wsschema/phase-response.js';
import { PingMediaPlaneRequest } from '../wsschema/ping-media-plane-request.js';
import { PingMediaPlaneResponse } from '../wsschema/ping-media-plane-response.js';
import { PingMediaPlaneUnreliableRequest } from '../wsschema/ping-media-plane-unreliable-request.js';
import { PingMediaPlaneUnreliableResponse } from '../wsschema/ping-media-plane-unreliable-response.js';
import { PingServerRequest } from '../wsschema/ping-server-request.js';
import { PingServerResponse } from '../wsschema/ping-server-response.js';
import { PingServerUnreliableRequest } from '../wsschema/ping-server-unreliable-request.js';
import { PingServerUnreliableResponse } from '../wsschema/ping-server-unreliable-response.js';
import { PlayerNameRequest } from '../wsschema/player-name-request.js';
import { PlayerNameResponse } from '../wsschema/player-name-response.js';
import { PlayerScoreResponse } from '../wsschema/player-score-response.js';
import { RepeaterBinaryResponse } from '../wsschema/repeater-binary-response.js';
import { RepeaterBroadcastBinaryResponse } from '../wsschema/repeater-broadcast-binary-response.js';
import { RepeaterLoginRequest } from '../wsschema/repeater-login-request.js';
import { ShapeRequest } from '../wsschema/shape-request.js';
import { ShapeResponse } from '../wsschema/shape-response.js';
import { TIMHitEvent } from '../wsschema/timhit-event.js';
import { TIMInteractableData } from '../wsschema/timinteractable-data.js';
import { TIMInteractableUpdate } from '../wsschema/timinteractable-update.js';
import { TIMMappedAreaAdd } from '../wsschema/timmapped-area-add.js';
import { TIMMappedAreaRemoved } from '../wsschema/timmapped-area-removed.js';
import { TIMMappedAreaUpdate } from '../wsschema/timmapped-area-update.js';
import { TIMPlayerInput } from '../wsschema/timplayer-input.js';
import { WebClientLoginRequest } from '../wsschema/web-client-login-request.js';
import { WebClientLoginResponse } from '../wsschema/web-client-login-response.js';
import { WebClientLogoutRequest } from '../wsschema/web-client-logout-request.js';


export enum Message {
  NONE = 0,
  PingServerRequest = 1,
  PingServerResponse = 2,
  PingServerUnreliableRequest = 3,
  PingServerUnreliableResponse = 4,
  PingMediaPlaneRequest = 5,
  PingMediaPlaneResponse = 6,
  PingMediaPlaneUnreliableRequest = 7,
  PingMediaPlaneUnreliableResponse = 8,
  ClientLoginResponse = 9,
  MediaPlaneLoginRequest = 10,
  MobileToMediaPlaneLoginRequest = 11,
  MobileToMediaPlaneLogoutRequest = 12,
  JsonToBinaryRequest = 13,
  JsonToBinaryResponse = 14,
  RepeaterLoginRequest = 15,
  WebClientLoginRequest = 16,
  WebClientLoginResponse = 17,
  WebClientLogoutRequest = 18,
  RepeaterBinaryResponse = 19,
  RepeaterBroadcastBinaryResponse = 20,
  GenericBatchRequest = 21,
  GenericBatchResponse = 22,
  LateConnectPayloadRequest = 23,
  LateConnectPayloadResponse = 24,
  ShapeRequest = 25,
  ShapeResponse = 26,
  PlayerNameRequest = 27,
  PlayerNameResponse = 28,
  PhaseResponse = 29,
  GlobalInputResponse = 30,
  PlayerScoreResponse = 31,
  TIMPlayerInput = 32,
  TIMMappedAreaAdd = 33,
  TIMMappedAreaUpdate = 34,
  TIMMappedAreaRemoved = 35,
  TIMInteractableData = 36,
  TIMInteractableUpdate = 37,
  TIMHitEvent = 38
}

export function unionToMessage(
  type: Message,
  accessor: (obj:ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|GlobalInputResponse|JsonToBinaryRequest|JsonToBinaryResponse|LateConnectPayloadRequest|LateConnectPayloadResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PhaseResponse|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerNameRequest|PlayerNameResponse|PlayerScoreResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|ShapeRequest|ShapeResponse|TIMHitEvent|TIMInteractableData|TIMInteractableUpdate|TIMMappedAreaAdd|TIMMappedAreaRemoved|TIMMappedAreaUpdate|TIMPlayerInput|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest) => ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|GlobalInputResponse|JsonToBinaryRequest|JsonToBinaryResponse|LateConnectPayloadRequest|LateConnectPayloadResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PhaseResponse|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerNameRequest|PlayerNameResponse|PlayerScoreResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|ShapeRequest|ShapeResponse|TIMHitEvent|TIMInteractableData|TIMInteractableUpdate|TIMMappedAreaAdd|TIMMappedAreaRemoved|TIMMappedAreaUpdate|TIMPlayerInput|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null
): ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|GlobalInputResponse|JsonToBinaryRequest|JsonToBinaryResponse|LateConnectPayloadRequest|LateConnectPayloadResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PhaseResponse|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerNameRequest|PlayerNameResponse|PlayerScoreResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|ShapeRequest|ShapeResponse|TIMHitEvent|TIMInteractableData|TIMInteractableUpdate|TIMMappedAreaAdd|TIMMappedAreaRemoved|TIMMappedAreaUpdate|TIMPlayerInput|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null {
  switch(Message[type]) {
    case 'NONE': return null; 
    case 'PingServerRequest': return accessor(new PingServerRequest())! as PingServerRequest;
    case 'PingServerResponse': return accessor(new PingServerResponse())! as PingServerResponse;
    case 'PingServerUnreliableRequest': return accessor(new PingServerUnreliableRequest())! as PingServerUnreliableRequest;
    case 'PingServerUnreliableResponse': return accessor(new PingServerUnreliableResponse())! as PingServerUnreliableResponse;
    case 'PingMediaPlaneRequest': return accessor(new PingMediaPlaneRequest())! as PingMediaPlaneRequest;
    case 'PingMediaPlaneResponse': return accessor(new PingMediaPlaneResponse())! as PingMediaPlaneResponse;
    case 'PingMediaPlaneUnreliableRequest': return accessor(new PingMediaPlaneUnreliableRequest())! as PingMediaPlaneUnreliableRequest;
    case 'PingMediaPlaneUnreliableResponse': return accessor(new PingMediaPlaneUnreliableResponse())! as PingMediaPlaneUnreliableResponse;
    case 'ClientLoginResponse': return accessor(new ClientLoginResponse())! as ClientLoginResponse;
    case 'MediaPlaneLoginRequest': return accessor(new MediaPlaneLoginRequest())! as MediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLoginRequest': return accessor(new MobileToMediaPlaneLoginRequest())! as MobileToMediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLogoutRequest': return accessor(new MobileToMediaPlaneLogoutRequest())! as MobileToMediaPlaneLogoutRequest;
    case 'JsonToBinaryRequest': return accessor(new JsonToBinaryRequest())! as JsonToBinaryRequest;
    case 'JsonToBinaryResponse': return accessor(new JsonToBinaryResponse())! as JsonToBinaryResponse;
    case 'RepeaterLoginRequest': return accessor(new RepeaterLoginRequest())! as RepeaterLoginRequest;
    case 'WebClientLoginRequest': return accessor(new WebClientLoginRequest())! as WebClientLoginRequest;
    case 'WebClientLoginResponse': return accessor(new WebClientLoginResponse())! as WebClientLoginResponse;
    case 'WebClientLogoutRequest': return accessor(new WebClientLogoutRequest())! as WebClientLogoutRequest;
    case 'RepeaterBinaryResponse': return accessor(new RepeaterBinaryResponse())! as RepeaterBinaryResponse;
    case 'RepeaterBroadcastBinaryResponse': return accessor(new RepeaterBroadcastBinaryResponse())! as RepeaterBroadcastBinaryResponse;
    case 'GenericBatchRequest': return accessor(new GenericBatchRequest())! as GenericBatchRequest;
    case 'GenericBatchResponse': return accessor(new GenericBatchResponse())! as GenericBatchResponse;
    case 'LateConnectPayloadRequest': return accessor(new LateConnectPayloadRequest())! as LateConnectPayloadRequest;
    case 'LateConnectPayloadResponse': return accessor(new LateConnectPayloadResponse())! as LateConnectPayloadResponse;
    case 'ShapeRequest': return accessor(new ShapeRequest())! as ShapeRequest;
    case 'ShapeResponse': return accessor(new ShapeResponse())! as ShapeResponse;
    case 'PlayerNameRequest': return accessor(new PlayerNameRequest())! as PlayerNameRequest;
    case 'PlayerNameResponse': return accessor(new PlayerNameResponse())! as PlayerNameResponse;
    case 'PhaseResponse': return accessor(new PhaseResponse())! as PhaseResponse;
    case 'GlobalInputResponse': return accessor(new GlobalInputResponse())! as GlobalInputResponse;
    case 'PlayerScoreResponse': return accessor(new PlayerScoreResponse())! as PlayerScoreResponse;
    case 'TIMPlayerInput': return accessor(new TIMPlayerInput())! as TIMPlayerInput;
    case 'TIMMappedAreaAdd': return accessor(new TIMMappedAreaAdd())! as TIMMappedAreaAdd;
    case 'TIMMappedAreaUpdate': return accessor(new TIMMappedAreaUpdate())! as TIMMappedAreaUpdate;
    case 'TIMMappedAreaRemoved': return accessor(new TIMMappedAreaRemoved())! as TIMMappedAreaRemoved;
    case 'TIMInteractableData': return accessor(new TIMInteractableData())! as TIMInteractableData;
    case 'TIMInteractableUpdate': return accessor(new TIMInteractableUpdate())! as TIMInteractableUpdate;
    case 'TIMHitEvent': return accessor(new TIMHitEvent())! as TIMHitEvent;
    default: return null;
  }
}

export function unionListToMessage(
  type: Message, 
  accessor: (index: number, obj:ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|GlobalInputResponse|JsonToBinaryRequest|JsonToBinaryResponse|LateConnectPayloadRequest|LateConnectPayloadResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PhaseResponse|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerNameRequest|PlayerNameResponse|PlayerScoreResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|ShapeRequest|ShapeResponse|TIMHitEvent|TIMInteractableData|TIMInteractableUpdate|TIMMappedAreaAdd|TIMMappedAreaRemoved|TIMMappedAreaUpdate|TIMPlayerInput|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest) => ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|GlobalInputResponse|JsonToBinaryRequest|JsonToBinaryResponse|LateConnectPayloadRequest|LateConnectPayloadResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PhaseResponse|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerNameRequest|PlayerNameResponse|PlayerScoreResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|ShapeRequest|ShapeResponse|TIMHitEvent|TIMInteractableData|TIMInteractableUpdate|TIMMappedAreaAdd|TIMMappedAreaRemoved|TIMMappedAreaUpdate|TIMPlayerInput|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null, 
  index: number
): ClientLoginResponse|GenericBatchRequest|GenericBatchResponse|GlobalInputResponse|JsonToBinaryRequest|JsonToBinaryResponse|LateConnectPayloadRequest|LateConnectPayloadResponse|MediaPlaneLoginRequest|MobileToMediaPlaneLoginRequest|MobileToMediaPlaneLogoutRequest|PhaseResponse|PingMediaPlaneRequest|PingMediaPlaneResponse|PingMediaPlaneUnreliableRequest|PingMediaPlaneUnreliableResponse|PingServerRequest|PingServerResponse|PingServerUnreliableRequest|PingServerUnreliableResponse|PlayerNameRequest|PlayerNameResponse|PlayerScoreResponse|RepeaterBinaryResponse|RepeaterBroadcastBinaryResponse|RepeaterLoginRequest|ShapeRequest|ShapeResponse|TIMHitEvent|TIMInteractableData|TIMInteractableUpdate|TIMMappedAreaAdd|TIMMappedAreaRemoved|TIMMappedAreaUpdate|TIMPlayerInput|WebClientLoginRequest|WebClientLoginResponse|WebClientLogoutRequest|null {
  switch(Message[type]) {
    case 'NONE': return null; 
    case 'PingServerRequest': return accessor(index, new PingServerRequest())! as PingServerRequest;
    case 'PingServerResponse': return accessor(index, new PingServerResponse())! as PingServerResponse;
    case 'PingServerUnreliableRequest': return accessor(index, new PingServerUnreliableRequest())! as PingServerUnreliableRequest;
    case 'PingServerUnreliableResponse': return accessor(index, new PingServerUnreliableResponse())! as PingServerUnreliableResponse;
    case 'PingMediaPlaneRequest': return accessor(index, new PingMediaPlaneRequest())! as PingMediaPlaneRequest;
    case 'PingMediaPlaneResponse': return accessor(index, new PingMediaPlaneResponse())! as PingMediaPlaneResponse;
    case 'PingMediaPlaneUnreliableRequest': return accessor(index, new PingMediaPlaneUnreliableRequest())! as PingMediaPlaneUnreliableRequest;
    case 'PingMediaPlaneUnreliableResponse': return accessor(index, new PingMediaPlaneUnreliableResponse())! as PingMediaPlaneUnreliableResponse;
    case 'ClientLoginResponse': return accessor(index, new ClientLoginResponse())! as ClientLoginResponse;
    case 'MediaPlaneLoginRequest': return accessor(index, new MediaPlaneLoginRequest())! as MediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLoginRequest': return accessor(index, new MobileToMediaPlaneLoginRequest())! as MobileToMediaPlaneLoginRequest;
    case 'MobileToMediaPlaneLogoutRequest': return accessor(index, new MobileToMediaPlaneLogoutRequest())! as MobileToMediaPlaneLogoutRequest;
    case 'JsonToBinaryRequest': return accessor(index, new JsonToBinaryRequest())! as JsonToBinaryRequest;
    case 'JsonToBinaryResponse': return accessor(index, new JsonToBinaryResponse())! as JsonToBinaryResponse;
    case 'RepeaterLoginRequest': return accessor(index, new RepeaterLoginRequest())! as RepeaterLoginRequest;
    case 'WebClientLoginRequest': return accessor(index, new WebClientLoginRequest())! as WebClientLoginRequest;
    case 'WebClientLoginResponse': return accessor(index, new WebClientLoginResponse())! as WebClientLoginResponse;
    case 'WebClientLogoutRequest': return accessor(index, new WebClientLogoutRequest())! as WebClientLogoutRequest;
    case 'RepeaterBinaryResponse': return accessor(index, new RepeaterBinaryResponse())! as RepeaterBinaryResponse;
    case 'RepeaterBroadcastBinaryResponse': return accessor(index, new RepeaterBroadcastBinaryResponse())! as RepeaterBroadcastBinaryResponse;
    case 'GenericBatchRequest': return accessor(index, new GenericBatchRequest())! as GenericBatchRequest;
    case 'GenericBatchResponse': return accessor(index, new GenericBatchResponse())! as GenericBatchResponse;
    case 'LateConnectPayloadRequest': return accessor(index, new LateConnectPayloadRequest())! as LateConnectPayloadRequest;
    case 'LateConnectPayloadResponse': return accessor(index, new LateConnectPayloadResponse())! as LateConnectPayloadResponse;
    case 'ShapeRequest': return accessor(index, new ShapeRequest())! as ShapeRequest;
    case 'ShapeResponse': return accessor(index, new ShapeResponse())! as ShapeResponse;
    case 'PlayerNameRequest': return accessor(index, new PlayerNameRequest())! as PlayerNameRequest;
    case 'PlayerNameResponse': return accessor(index, new PlayerNameResponse())! as PlayerNameResponse;
    case 'PhaseResponse': return accessor(index, new PhaseResponse())! as PhaseResponse;
    case 'GlobalInputResponse': return accessor(index, new GlobalInputResponse())! as GlobalInputResponse;
    case 'PlayerScoreResponse': return accessor(index, new PlayerScoreResponse())! as PlayerScoreResponse;
    case 'TIMPlayerInput': return accessor(index, new TIMPlayerInput())! as TIMPlayerInput;
    case 'TIMMappedAreaAdd': return accessor(index, new TIMMappedAreaAdd())! as TIMMappedAreaAdd;
    case 'TIMMappedAreaUpdate': return accessor(index, new TIMMappedAreaUpdate())! as TIMMappedAreaUpdate;
    case 'TIMMappedAreaRemoved': return accessor(index, new TIMMappedAreaRemoved())! as TIMMappedAreaRemoved;
    case 'TIMInteractableData': return accessor(index, new TIMInteractableData())! as TIMInteractableData;
    case 'TIMInteractableUpdate': return accessor(index, new TIMInteractableUpdate())! as TIMInteractableUpdate;
    case 'TIMHitEvent': return accessor(index, new TIMHitEvent())! as TIMHitEvent;
    default: return null;
  }
}
