// automatically generated by the FlatBuffers compiler, do not modify

export enum PhaseEnums {
  Min = 0,
  Intro = 1,
  IntroCountdown = 2,
  Tutorial = 3,
  WarpVote = 4,
  AsteroidWaveOne = 5,
  AsteroidWaveOneLeaderboard = 6,
  AsteroidWaveTwo = 7,
  AsteroidWaveTwoLeaderboard = 8,
  AsteroidWaveThree = 9,
  AsteroidWaveThreeLeaderboard = 10,
  SaveTheShip = 11,
  FinalLeaderboard = 12,
  Outro = 13,
  Max = 14
}
