// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PlayerScoreResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerScoreResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerScoreResponse(bb:flatbuffers.ByteBuffer, obj?:PlayerScoreResponse):PlayerScoreResponse {
  return (obj || new PlayerScoreResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerScoreResponse(bb:flatbuffers.ByteBuffer, obj?:PlayerScoreResponse):PlayerScoreResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerScoreResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

newScore():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPlayerScoreResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addNewScore(builder:flatbuffers.Builder, newScore:number) {
  builder.addFieldFloat32(1, newScore, 0.0);
}

static endPlayerScoreResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerScoreResponse(builder:flatbuffers.Builder, sessionId:number, newScore:number):flatbuffers.Offset {
  PlayerScoreResponse.startPlayerScoreResponse(builder);
  PlayerScoreResponse.addSessionId(builder, sessionId);
  PlayerScoreResponse.addNewScore(builder, newScore);
  return PlayerScoreResponse.endPlayerScoreResponse(builder);
}
}
