// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class PointTapResetRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PointTapResetRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPointTapResetRequest(bb:flatbuffers.ByteBuffer, obj?:PointTapResetRequest):PointTapResetRequest {
  return (obj || new PointTapResetRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPointTapResetRequest(bb:flatbuffers.ByteBuffer, obj?:PointTapResetRequest):PointTapResetRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PointTapResetRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startPointTapResetRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static endPointTapResetRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPointTapResetRequest(builder:flatbuffers.Builder, sessionId:number):flatbuffers.Offset {
  PointTapResetRequest.startPointTapResetRequest(builder);
  PointTapResetRequest.addSessionId(builder, sessionId);
  return PointTapResetRequest.endPointTapResetRequest(builder);
}
}
