"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.ShapeRequest = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var flatbuffers = require("flatbuffers");
var ShapeRequest = /** @class */ (function () {
    function ShapeRequest() {
        this.bb = null;
        this.bb_pos = 0;
    }
    ShapeRequest.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    ShapeRequest.getRootAsShapeRequest = function (bb, obj) {
        return (obj || new ShapeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ShapeRequest.getSizePrefixedRootAsShapeRequest = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ShapeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    ShapeRequest.prototype.sessionId = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    ShapeRequest.prototype.shapeId = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    ShapeRequest.startShapeRequest = function (builder) {
        builder.startObject(2);
    };
    ShapeRequest.addSessionId = function (builder, sessionId) {
        builder.addFieldInt32(0, sessionId, 0);
    };
    ShapeRequest.addShapeId = function (builder, shapeId) {
        builder.addFieldInt32(1, shapeId, 0);
    };
    ShapeRequest.endShapeRequest = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    ShapeRequest.createShapeRequest = function (builder, sessionId, shapeId) {
        ShapeRequest.startShapeRequest(builder);
        ShapeRequest.addSessionId(builder, sessionId);
        ShapeRequest.addShapeId(builder, shapeId);
        return ShapeRequest.endShapeRequest(builder);
    };
    return ShapeRequest;
}());
exports.ShapeRequest = ShapeRequest;
//# sourceMappingURL=shape-request.js.map