// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SlashResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SlashResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSlashResponse(bb:flatbuffers.ByteBuffer, obj?:SlashResponse):SlashResponse {
  return (obj || new SlashResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSlashResponse(bb:flatbuffers.ByteBuffer, obj?:SlashResponse):SlashResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SlashResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

playerScore():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startSlashResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addPlayerScore(builder:flatbuffers.Builder, playerScore:number) {
  builder.addFieldInt32(1, playerScore, 0);
}

static endSlashResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSlashResponse(builder:flatbuffers.Builder, sessionId:number, playerScore:number):flatbuffers.Offset {
  SlashResponse.startSlashResponse(builder);
  SlashResponse.addSessionId(builder, sessionId);
  SlashResponse.addPlayerScore(builder, playerScore);
  return SlashResponse.endSlashResponse(builder);
}
}
