"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.SlashRequest = void 0;
var flatbuffers = require("flatbuffers");
var SlashRequest = /** @class */ (function () {
    function SlashRequest() {
        this.bb = null;
        this.bb_pos = 0;
    }
    SlashRequest.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    SlashRequest.getRootAsSlashRequest = function (bb, obj) {
        return (obj || new SlashRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SlashRequest.getSizePrefixedRootAsSlashRequest = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new SlashRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    SlashRequest.prototype.sessionId = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    SlashRequest.prototype.slashId = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    SlashRequest.startSlashRequest = function (builder) {
        builder.startObject(2);
    };
    SlashRequest.addSessionId = function (builder, sessionId) {
        builder.addFieldInt32(0, sessionId, 0);
    };
    SlashRequest.addSlashId = function (builder, slashId) {
        builder.addFieldInt32(1, slashId, 0);
    };
    SlashRequest.endSlashRequest = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    SlashRequest.createSlashRequest = function (builder, sessionId, slashId) {
        SlashRequest.startSlashRequest(builder);
        SlashRequest.addSessionId(builder, sessionId);
        SlashRequest.addSlashId(builder, slashId);
        return SlashRequest.endSlashRequest(builder);
    };
    return SlashRequest;
}());
exports.SlashRequest = SlashRequest;
//# sourceMappingURL=slash-request.js.map