// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TapAsteroidRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TapAsteroidRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTapAsteroidRequest(bb:flatbuffers.ByteBuffer, obj?:TapAsteroidRequest):TapAsteroidRequest {
  return (obj || new TapAsteroidRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTapAsteroidRequest(bb:flatbuffers.ByteBuffer, obj?:TapAsteroidRequest):TapAsteroidRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TapAsteroidRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

zoneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

asteroidId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startTapAsteroidRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addZoneId(builder:flatbuffers.Builder, zoneId:number) {
  builder.addFieldInt8(1, zoneId, 0);
}

static addAsteroidId(builder:flatbuffers.Builder, asteroidId:number) {
  builder.addFieldInt16(2, asteroidId, 0);
}

static endTapAsteroidRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTapAsteroidRequest(builder:flatbuffers.Builder, sessionId:number, zoneId:number, asteroidId:number):flatbuffers.Offset {
  TapAsteroidRequest.startTapAsteroidRequest(builder);
  TapAsteroidRequest.addSessionId(builder, sessionId);
  TapAsteroidRequest.addZoneId(builder, zoneId);
  TapAsteroidRequest.addAsteroidId(builder, asteroidId);
  return TapAsteroidRequest.endTapAsteroidRequest(builder);
}
}
