// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TapAsteroidInfoResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TapAsteroidInfoResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTapAsteroidInfoResponse(bb:flatbuffers.ByteBuffer, obj?:TapAsteroidInfoResponse):TapAsteroidInfoResponse {
  return (obj || new TapAsteroidInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTapAsteroidInfoResponse(bb:flatbuffers.ByteBuffer, obj?:TapAsteroidInfoResponse):TapAsteroidInfoResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TapAsteroidInfoResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

zoneId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

asteroidId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

scaledX():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

scaledY():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startTapAsteroidInfoResponse(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addZoneId(builder:flatbuffers.Builder, zoneId:number) {
  builder.addFieldInt8(1, zoneId, 0);
}

static addAsteroidId(builder:flatbuffers.Builder, asteroidId:number) {
  builder.addFieldInt16(2, asteroidId, 0);
}

static addScaledX(builder:flatbuffers.Builder, scaledX:number) {
  builder.addFieldFloat32(3, scaledX, 0.0);
}

static addScaledY(builder:flatbuffers.Builder, scaledY:number) {
  builder.addFieldFloat32(4, scaledY, 0.0);
}

static endTapAsteroidInfoResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTapAsteroidInfoResponse(builder:flatbuffers.Builder, sessionId:number, zoneId:number, asteroidId:number, scaledX:number, scaledY:number):flatbuffers.Offset {
  TapAsteroidInfoResponse.startTapAsteroidInfoResponse(builder);
  TapAsteroidInfoResponse.addSessionId(builder, sessionId);
  TapAsteroidInfoResponse.addZoneId(builder, zoneId);
  TapAsteroidInfoResponse.addAsteroidId(builder, asteroidId);
  TapAsteroidInfoResponse.addScaledX(builder, scaledX);
  TapAsteroidInfoResponse.addScaledY(builder, scaledY);
  return TapAsteroidInfoResponse.endTapAsteroidInfoResponse(builder);
}
}
