"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TIMInteractableUpdate = void 0;
var flatbuffers = __importStar(require("flatbuffers"));
var vec2_js_1 = require("../wsschema/vec2.js");
var TIMInteractableUpdate = /** @class */ (function () {
    function TIMInteractableUpdate() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TIMInteractableUpdate.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TIMInteractableUpdate.getRootAsTIMInteractableUpdate = function (bb, obj) {
        return (obj || new TIMInteractableUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TIMInteractableUpdate.getSizePrefixedRootAsTIMInteractableUpdate = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new TIMInteractableUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TIMInteractableUpdate.prototype.sessionId = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    TIMInteractableUpdate.prototype.netHandle = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    };
    TIMInteractableUpdate.prototype.location = function (obj) {
        var offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? (obj || new vec2_js_1.Vec2()).__init(this.bb_pos + offset, this.bb) : null;
    };
    TIMInteractableUpdate.prototype.rotation = function () {
        var offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    };
    TIMInteractableUpdate.prototype.distance = function () {
        var offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    };
    TIMInteractableUpdate.prototype.tags = function (index, optionalEncoding) {
        var offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
    };
    TIMInteractableUpdate.prototype.tagsLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    TIMInteractableUpdate.startTIMInteractableUpdate = function (builder) {
        builder.startObject(6);
    };
    TIMInteractableUpdate.addSessionId = function (builder, sessionId) {
        builder.addFieldInt32(0, sessionId, 0);
    };
    TIMInteractableUpdate.addNetHandle = function (builder, netHandle) {
        builder.addFieldInt32(1, netHandle, 0);
    };
    TIMInteractableUpdate.addLocation = function (builder, locationOffset) {
        builder.addFieldStruct(2, locationOffset, 0);
    };
    TIMInteractableUpdate.addRotation = function (builder, rotation) {
        builder.addFieldFloat32(3, rotation, 0.0);
    };
    TIMInteractableUpdate.addDistance = function (builder, distance) {
        builder.addFieldFloat32(4, distance, 0.0);
    };
    TIMInteractableUpdate.addTags = function (builder, tagsOffset) {
        builder.addFieldOffset(5, tagsOffset, 0);
    };
    TIMInteractableUpdate.createTagsVector = function (builder, data) {
        builder.startVector(4, data.length, 4);
        for (var i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    };
    TIMInteractableUpdate.startTagsVector = function (builder, numElems) {
        builder.startVector(4, numElems, 4);
    };
    TIMInteractableUpdate.endTIMInteractableUpdate = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    return TIMInteractableUpdate;
}());
exports.TIMInteractableUpdate = TIMInteractableUpdate;
//# sourceMappingURL=timinteractable-update.js.map