"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.TIMInputEvent = void 0;
var vec2_js_1 = require("../wsschema/vec2.js");
var TIMInputEvent = /** @class */ (function () {
    function TIMInputEvent() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TIMInputEvent.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TIMInputEvent.prototype.areaHandle = function () {
        return this.bb.readInt32(this.bb_pos);
    };
    TIMInputEvent.prototype.index = function () {
        return this.bb.readInt32(this.bb_pos + 4);
    };
    TIMInputEvent.prototype.location = function (obj) {
        return (obj || new vec2_js_1.Vec2()).__init(this.bb_pos + 8, this.bb);
    };
    TIMInputEvent.prototype.eventType = function () {
        return this.bb.readUint8(this.bb_pos + 16);
    };
    TIMInputEvent.prototype.time = function () {
        return this.bb.readFloat32(this.bb_pos + 20);
    };
    TIMInputEvent.sizeOf = function () {
        return 24;
    };
    TIMInputEvent.createTIMInputEvent = function (builder, area_handle, index, location_x, location_y, event_type, time) {
        builder.prep(4, 24);
        builder.writeFloat32(time);
        builder.pad(3);
        builder.writeInt8(event_type);
        builder.prep(4, 8);
        builder.writeFloat32(location_y);
        builder.writeFloat32(location_x);
        builder.writeInt32(index);
        builder.writeInt32(area_handle);
        return builder.offset();
    };
    return TIMInputEvent;
}());
exports.TIMInputEvent = TIMInputEvent;
//# sourceMappingURL=timinput-event.js.map