// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TIMInteractableDestroyed {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TIMInteractableDestroyed {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTIMInteractableDestroyed(bb:flatbuffers.ByteBuffer, obj?:TIMInteractableDestroyed):TIMInteractableDestroyed {
  return (obj || new TIMInteractableDestroyed()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTIMInteractableDestroyed(bb:flatbuffers.ByteBuffer, obj?:TIMInteractableDestroyed):TIMInteractableDestroyed {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TIMInteractableDestroyed()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

netHandle():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startTIMInteractableDestroyed(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addNetHandle(builder:flatbuffers.Builder, netHandle:number) {
  builder.addFieldInt32(1, netHandle, 0);
}

static endTIMInteractableDestroyed(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTIMInteractableDestroyed(builder:flatbuffers.Builder, sessionId:number, netHandle:number):flatbuffers.Offset {
  TIMInteractableDestroyed.startTIMInteractableDestroyed(builder);
  TIMInteractableDestroyed.addSessionId(builder, sessionId);
  TIMInteractableDestroyed.addNetHandle(builder, netHandle);
  return TIMInteractableDestroyed.endTIMInteractableDestroyed(builder);
}
}
