// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TIMInputInteractable {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TIMInputInteractable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTIMInputInteractable(bb:flatbuffers.ByteBuffer, obj?:TIMInputInteractable):TIMInputInteractable {
  return (obj || new TIMInputInteractable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTIMInputInteractable(bb:flatbuffers.ByteBuffer, obj?:TIMInputInteractable):TIMInputInteractable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TIMInputInteractable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

netHandle():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startTIMInputInteractable(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addNetHandle(builder:flatbuffers.Builder, netHandle:number) {
  builder.addFieldInt32(0, netHandle, 0);
}

static endTIMInputInteractable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTIMInputInteractable(builder:flatbuffers.Builder, netHandle:number):flatbuffers.Offset {
  TIMInputInteractable.startTIMInputInteractable(builder);
  TIMInputInteractable.addNetHandle(builder, netHandle);
  return TIMInputInteractable.endTIMInputInteractable(builder);
}
}
