// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TIMMappedAreaRemoved {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TIMMappedAreaRemoved {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTIMMappedAreaRemoved(bb:flatbuffers.ByteBuffer, obj?:TIMMappedAreaRemoved):TIMMappedAreaRemoved {
  return (obj || new TIMMappedAreaRemoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTIMMappedAreaRemoved(bb:flatbuffers.ByteBuffer, obj?:TIMMappedAreaRemoved):TIMMappedAreaRemoved {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TIMMappedAreaRemoved()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

handle():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startTIMMappedAreaRemoved(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSessionId(builder:flatbuffers.Builder, sessionId:number) {
  builder.addFieldInt32(0, sessionId, 0);
}

static addHandle(builder:flatbuffers.Builder, handle:number) {
  builder.addFieldInt32(1, handle, 0);
}

static endTIMMappedAreaRemoved(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTIMMappedAreaRemoved(builder:flatbuffers.Builder, sessionId:number, handle:number):flatbuffers.Offset {
  TIMMappedAreaRemoved.startTIMMappedAreaRemoved(builder);
  TIMMappedAreaRemoved.addSessionId(builder, sessionId);
  TIMMappedAreaRemoved.addHandle(builder, handle);
  return TIMMappedAreaRemoved.endTIMMappedAreaRemoved(builder);
}
}
