"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TIMPlayerInput = void 0;
var flatbuffers = __importStar(require("flatbuffers"));
var timinput_event_js_1 = require("../wsschema/timinput-event.js");
var TIMPlayerInput = /** @class */ (function () {
    function TIMPlayerInput() {
        this.bb = null;
        this.bb_pos = 0;
    }
    TIMPlayerInput.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    TIMPlayerInput.getRootAsTIMPlayerInput = function (bb, obj) {
        return (obj || new TIMPlayerInput()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TIMPlayerInput.getSizePrefixedRootAsTIMPlayerInput = function (bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new TIMPlayerInput()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    };
    TIMPlayerInput.prototype.sessionId = function () {
        var offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    };
    TIMPlayerInput.prototype.inputEvents = function (index, obj) {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new timinput_event_js_1.TIMInputEvent()).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
    };
    TIMPlayerInput.prototype.inputEventsLength = function () {
        var offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    };
    TIMPlayerInput.startTIMPlayerInput = function (builder) {
        builder.startObject(2);
    };
    TIMPlayerInput.addSessionId = function (builder, sessionId) {
        builder.addFieldInt32(0, sessionId, 0);
    };
    TIMPlayerInput.addInputEvents = function (builder, inputEventsOffset) {
        builder.addFieldOffset(1, inputEventsOffset, 0);
    };
    TIMPlayerInput.startInputEventsVector = function (builder, numElems) {
        builder.startVector(24, numElems, 4);
    };
    TIMPlayerInput.endTIMPlayerInput = function (builder) {
        var offset = builder.endObject();
        return offset;
    };
    TIMPlayerInput.createTIMPlayerInput = function (builder, sessionId, inputEventsOffset) {
        TIMPlayerInput.startTIMPlayerInput(builder);
        TIMPlayerInput.addSessionId(builder, sessionId);
        TIMPlayerInput.addInputEvents(builder, inputEventsOffset);
        return TIMPlayerInput.endTIMPlayerInput(builder);
    };
    return TIMPlayerInput;
}());
exports.TIMPlayerInput = TIMPlayerInput;
//# sourceMappingURL=timplayer-input.js.map