// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EButtonTypeEnum {
  None = 0,
  Reticle1 = 1,
  Reticle2 = 2,
  Reticle3 = 3,
  Reticle4 = 4,
  Max = 5
}
