// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ETriggerStateSchema {
  None = 0,
  Triggered = 1,
  Started = 2,
  Ongoing = 4,
  Canceled = 8,
  Completed = 16
}
