// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EWSGlobalInputTypes {
  Min = 0,
  None = 1,
  TapSlash = 2,
  Drawing = 3,
  Buttons = 4,
  TapAsteroid = 5,
  PointTap = 6,
  Slash = 7,
  Max = 8
}
