// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EWSModifyGlobalInputType {
  Min = 0,
  Normal = 1,
  LockOn = 2,
  Combo = 3,
  DynamicColor = 4,
  Max = 5
}
