"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.EWSPhaseEnums = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var EWSPhaseEnums;
(function (EWSPhaseEnums) {
    EWSPhaseEnums[EWSPhaseEnums["Min"] = 0] = "Min";
    EWSPhaseEnums[EWSPhaseEnums["None"] = 1] = "None";
    EWSPhaseEnums[EWSPhaseEnums["Intro"] = 2] = "Intro";
    EWSPhaseEnums[EWSPhaseEnums["IntroCountdown"] = 3] = "IntroCountdown";
    EWSPhaseEnums[EWSPhaseEnums["Tutorial"] = 4] = "Tutorial";
    EWSPhaseEnums[EWSPhaseEnums["WarpVote"] = 5] = "WarpVote";
    EWSPhaseEnums[EWSPhaseEnums["AsteroidWaveOne"] = 6] = "AsteroidWaveOne";
    EWSPhaseEnums[EWSPhaseEnums["AsteroidWaveOneLeaderboard"] = 7] = "AsteroidWaveOneLeaderboard";
    EWSPhaseEnums[EWSPhaseEnums["AsteroidWaveTwo"] = 8] = "AsteroidWaveTwo";
    EWSPhaseEnums[EWSPhaseEnums["AsteroidWaveTwoLeaderboard"] = 9] = "AsteroidWaveTwoLeaderboard";
    EWSPhaseEnums[EWSPhaseEnums["AsteroidWaveThree"] = 10] = "AsteroidWaveThree";
    EWSPhaseEnums[EWSPhaseEnums["AsteroidWaveThreeLeaderboard"] = 11] = "AsteroidWaveThreeLeaderboard";
    EWSPhaseEnums[EWSPhaseEnums["SaveTheShip"] = 12] = "SaveTheShip";
    EWSPhaseEnums[EWSPhaseEnums["FinalLeaderboard"] = 13] = "FinalLeaderboard";
    EWSPhaseEnums[EWSPhaseEnums["Outro"] = 14] = "Outro";
    EWSPhaseEnums[EWSPhaseEnums["Max"] = 15] = "Max";
})(EWSPhaseEnums || (exports.EWSPhaseEnums = EWSPhaseEnums = {}));
//# sourceMappingURL=ewsphase-enums.js.map