"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.EWSSlashTypes = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var EWSSlashTypes;
(function (EWSSlashTypes) {
    EWSSlashTypes[EWSSlashTypes["Slash_W"] = 0] = "Slash_W";
    EWSSlashTypes[EWSSlashTypes["Slash_NW"] = 1] = "Slash_NW";
    EWSSlashTypes[EWSSlashTypes["Slash_N"] = 2] = "Slash_N";
    EWSSlashTypes[EWSSlashTypes["Slash_NE"] = 3] = "Slash_NE";
    EWSSlashTypes[EWSSlashTypes["Slash_E"] = 4] = "Slash_E";
    EWSSlashTypes[EWSSlashTypes["Slash_SE"] = 5] = "Slash_SE";
    EWSSlashTypes[EWSSlashTypes["Slash_S"] = 6] = "Slash_S";
    EWSSlashTypes[EWSSlashTypes["Slash_SW"] = 7] = "Slash_SW";
    EWSSlashTypes[EWSSlashTypes["Slash_MAX"] = 8] = "Slash_MAX";
    EWSSlashTypes[EWSSlashTypes["Slash_NONE"] = 9] = "Slash_NONE";
})(EWSSlashTypes || (exports.EWSSlashTypes = EWSSlashTypes = {}));
//# sourceMappingURL=ewsslash-types.js.map