// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EWSSlashTypes {
  Slash_W = 0,
  Slash_NW = 1,
  Slash_N = 2,
  Slash_NE = 3,
  Slash_E = 4,
  Slash_SE = 5,
  Slash_S = 6,
  Slash_SW = 7,
  Slash_MAX = 8,
  Slash_NONE = 9
}
