// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum EWSSequenceSymbolTypes {
  Circle = 0,
  Triangle = 1,
  Square = 2,
  Cross = 3,
  Max = 4,
  None = 5
}
